# Prefix - Sets the prefix used when sending the link in the chat to the user.
# Text - Sets the prefix used when sending the link in the chat to the user.
# Color - Set the color of the 'Text' on the sign.
Chat:
  Prefix: '&8[&4SignURLs&8]'
Sign:
  Text: 'SignURLs'
  Color: '&1'