#|-----------------------------------------------------------|
#|-------------------Plugin Chat Options---------------------|
#|-----------------------------------------------------------|
#
# Prefix - Sets the prefix used when sending the link in the chat to the user.
#
Chat:
  Prefix: '&8[&4SignURLs&8]'
#
#|-----------------------------------------------------------|
#|-------------------Plugin Sign Options---------------------|
#|-----------------------------------------------------------|
#
# Text - Sets the prefix used when sending the link in the chat to the user.
# Color - Set the color of the 'Text' on the sign.
#
Sign:
  Text: 'SignURLs'
  Color: '&1'